version: '3'

services:
  node:
    container_name: wmms_app
    image: node:18-alpine
    user: node
    restart: unless-stopped
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    ports:
      - '9079:9079'
    command: 'npm start'
    depends_on:
      - db

  db:
    container_name: wmms_mysql
    image: mysql:8.1
    restart: unless-stopped
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=+07:00
    volumes:
      - ./mysql/data/:/var/lib/mysql
    env_file:
      - ./mysql/db.env
    expose:
      - '3306'
  
  phpmyadmin:
    container_name: wmms_phpmyadmin
    image: phpmyadmin:5.2.1-apache
    restart: unless-stopped
    ports:
      - 9078:80
    environment:
      - PMA_HOST=db